import { ENDPOINTS, TITLES, DISPLAY_TYPES } from "./constants";
import { DashboardGridItem } from "./dashboard-grid-item.interface";

export const cardMap: Record<string, DashboardGridItem> = {
  'Avg Pageviews per Session': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 20,
    endpoint: ENDPOINTS.AVG_PAGEVIEWS_PER_SESSION,
    title: TITLES.AVG_PAGEVIEWS_PER_SESSION,
    displayType: DISPLAY_TYPES.SINGLE,
  },
  'Avg Time on Page': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 20,
    endpoint: ENDPOINTS.AVG_TIME_ON_PAGE,
    title: TITLES.AVG_TIME_ON_PAGE,
    displayType: DISPLAY_TYPES.SINGLE,
  },
  'Bounce Rate': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 22,
    endpoint: ENDPOINTS.BOUNCE_RATE,
    title: TITLES.BOUNCE_RATE,
    displayType: DISPLAY_TYPES.SINGLE,
  },
  'Bounce Rate by Title': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 22,
    endpoint: ENDPOINTS.BOUNCE_RATE_BY_TITLE,
    title: TITLES.BOUNCE_RATE_BY_TITLE,
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Events by Date': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 24,
    endpoint: ENDPOINTS.EVENTS_GROUPED,
    title: TITLES.EVENTS_BY_DATE,
    groupBy: 'date',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Events by Name': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 10,
    endpoint: ENDPOINTS.EVENTS_GROUPED,
    title: TITLES.EVENTS_BY_NAME,
    groupBy: 'name',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Events by URL': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 10,
    endpoint: ENDPOINTS.EVENTS_GROUPED,
    title: TITLES.EVENTS_BY_URL,
    groupBy: 'url',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Items by Category': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 16,
    endpoint: ENDPOINTS.ITEMS_GROUPED,
    title: TITLES.ITEMS_BY_CATEGORY,
    groupBy: 'category',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Items by Date': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 24,
    endpoint: ENDPOINTS.ITEMS_GROUPED,
    title: TITLES.ITEMS_BY_DATE,
    groupBy: 'date',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Items by ID': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 16,
    endpoint: ENDPOINTS.ITEMS_GROUPED,
    title: TITLES.ITEMS_BY_ID,
    groupBy: 'id',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Items by Name': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 18,
    endpoint: ENDPOINTS.ITEMS_GROUPED,
    title: TITLES.ITEMS_BY_NAME,
    groupBy: 'name',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Overview Summary': {
    cols: 1,
    rows: 2,
    x: 0,
    y: 0,
    endpoint: ENDPOINTS.OVERVIEW,
    title: TITLES.OVERVIEW,
    displayType: DISPLAY_TYPES.SUMMARY,
  },
  'Pages by Date': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 26,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.PAGES_BY_DATE,
    groupBy: 'date',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Pages by Referrer': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 4,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.PAGES_BY_REFERRER,
    groupBy: 'referrer',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Pages by Title': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 2,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.PAGES_BY_TITLE,
    groupBy: 'title',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Pages by URL': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 2,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.PAGES_BY_URL,
    groupBy: 'url',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Sessions by Browser': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 28,
    endpoint: ENDPOINTS.SESSIONS_GROUPED,
    title: TITLES.SESSIONS_BY_BROWSER,
    groupBy: 'browser',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Sessions by City': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 28,
    endpoint: ENDPOINTS.SESSIONS_GROUPED,
    title: TITLES.SESSIONS_BY_CITY,
    groupBy: 'city',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Sessions by Country': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 30,
    endpoint: ENDPOINTS.SESSIONS_GROUPED,
    title: TITLES.SESSIONS_BY_COUNTRY,
    groupBy: 'country',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Sessions by Date': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 30,
    endpoint: ENDPOINTS.SESSIONS_GROUPED,
    title: TITLES.SESSIONS_BY_DATE,
    groupBy: 'date',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Sessions by Device': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 32,
    endpoint: ENDPOINTS.SESSIONS_GROUPED,
    title: TITLES.SESSIONS_BY_DEVICE,
    groupBy: 'device',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Sessions by OS': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 32,
    endpoint: ENDPOINTS.SESSIONS_GROUPED,
    title: TITLES.SESSIONS_BY_OS,
    groupBy: 'os',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Sessions by Source': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 34,
    endpoint: ENDPOINTS.SESSIONS_GROUPED,
    title: TITLES.SESSIONS_BY_SOURCE,
    groupBy: 'source',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Top Exit Pages': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 34,
    endpoint: ENDPOINTS.TOP_EXIT_PAGES,
    title: TITLES.TOP_EXIT_PAGES,
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Top Landing Pages': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 36,
    endpoint: ENDPOINTS.TOP_LANDING_PAGES,
    title: TITLES.TOP_LANDING_PAGES,
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Traffic by Campaign': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 14,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.TRAFFIC_BY_CAMPAIGN,
    groupBy: 'campaign',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Traffic by Date': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 36,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.TRAFFIC_BY_DATE,
    groupBy: 'date',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Traffic by Medium': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 12,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.TRAFFIC_BY_MEDIUM,
    groupBy: 'medium',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Traffic by Source': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 12,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.TRAFFIC_BY_SOURCE,
    groupBy: 'source',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Unique Pageviews': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 38,
    endpoint: ENDPOINTS.UNIQUE_PAGE_VIEWS,
    title: TITLES.UNIQUE_PAGE_VIEWS,
    displayType: DISPLAY_TYPES.SINGLE,
  },
  'Visitors by Browser': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 8,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_BROWSER,
    groupBy: 'browser',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Visitors by City': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 6,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_CITY,
    groupBy: 'city',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Visitors by Country': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 4,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_COUNTRY,
    groupBy: 'country',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Visitors by Device': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 6,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_DEVICE,
    groupBy: 'device',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Visitors by OS': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 8,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_OS,
    groupBy: 'os',
    displayType: DISPLAY_TYPES.TABLE,
  }
};
