import { ENDPOINTS, TITLES, DISPLAY_TYPES } from "./constants";
import { DashboardGridItem } from "./dashboard-grid-item.interface";

export const cardMap: Record<string, DashboardGridItem> = {
  'Events by Name': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 10,
    endpoint: ENDPOINTS.EVENTS_GROUPED,
    title: TITLES.EVENTS_BY_NAME,
    groupBy: 'name',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Events by URL': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 10,
    endpoint: ENDPOINTS.EVENTS_GROUPED,
    title: TITLES.EVENTS_BY_URL,
    groupBy: 'url',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Items by Category': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 16,
    endpoint: ENDPOINTS.ITEMS_GROUPED,
    title: TITLES.ITEMS_BY_CATEGORY,
    groupBy: 'category',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Items by ID': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 16,
    endpoint: ENDPOINTS.ITEMS_GROUPED,
    title: TITLES.ITEMS_BY_ID,
    groupBy: 'id',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Items by Name': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 18,
    endpoint: ENDPOINTS.ITEMS_GROUPED,
    title: TITLES.ITEMS_BY_NAME,
    groupBy: 'name',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Overview Summary': {
    cols: 1,
    rows: 2,
    x: 0,
    y: 0,
    endpoint: ENDPOINTS.OVERVIEW,
    title: TITLES.OVERVIEW,
    displayType: DISPLAY_TYPES.SUMMARY,
  },
  'Pages by Referrer': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 4,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.PAGES_BY_REFERRER,
    groupBy: 'referrer',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Pages by Title': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 2,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.PAGES_BY_TITLE,
    groupBy: 'title',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Pages by URL': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 2,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.PAGES_BY_URL,
    groupBy: 'url',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Traffic by Campaign': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 14,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.TRAFFIC_BY_CAMPAIGN,
    groupBy: 'campaign',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Traffic by Medium': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 12,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.TRAFFIC_BY_MEDIUM,
    groupBy: 'medium',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Traffic by Source': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 12,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.TRAFFIC_BY_SOURCE,
    groupBy: 'source',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Visitors by Browser': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 8,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_BROWSER,
    groupBy: 'browser',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Visitors by City': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 6,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_CITY,
    groupBy: 'city',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Visitors by Country': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 4,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_COUNTRY,
    groupBy: 'country',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Visitors by Device': {
    cols: 2,
    rows: 2,
    x: 2,
    y: 6,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_DEVICE,
    groupBy: 'device',
    displayType: DISPLAY_TYPES.TABLE,
  },
  'Visitors by OS': {
    cols: 2,
    rows: 2,
    x: 0,
    y: 8,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_OS,
    groupBy: 'os',
    displayType: DISPLAY_TYPES.TABLE,
  }
};
