import { DashboardGridItem } from './dashboard-grid-item.interface';
import { ENDPOINTS, TITLES, EVENT_TYPES, DISPLAY_TYPES } from './constants';

export const ecommerceDashboard: DashboardGridItem[] = [
  {
    cols: 2,
    rows: 1,
    y: 0,
    x: 0,
    endpoint: ENDPOINTS.OVERVIEW,
    title: TITLES.OVERVIEW,
    displayType: DISPLAY_TYPES.SUMMARY,
  },
  {
    cols: 1,
    rows: 1,
    y: 0,
    x: 2,
    endpoint: ENDPOINTS.PAGEVIEWS,
    title: TITLES.PAGEVIEWS,
    event: EVENT_TYPES.PAGEVIEWS,
    displayType: DISPLAY_TYPES.REALTIME,
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 0,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.VIEWS_BY_TITLE,
    groupBy: 'title',
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 1,
    endpoint: ENDPOINTS.EVENTS_GROUPED,
    title: TITLES.EVENTS_BY_NAME,
    groupBy: 'name',
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 2,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_COUNTRY,
    groupBy: 'country',
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    y: 2,
    x: 0,
    endpoint: ENDPOINTS.ITEMS_GROUPED,
    title: TITLES.ITEMS_BY_NAME,
    groupBy: 'name',
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    y: 2,
    x: 1,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.SESSIONS_BY_SOURCE,
    groupBy: 'source',
    displayType: DISPLAY_TYPES.TABLE,
  },
];