import { DashboardGridItem } from './dashboard-grid-item.interface';
import { ENDPOINTS, TITLES } from './constants';

export const overviewDashboard: DashboardGridItem[] = [
  {
    cols: 2,
    rows: 1,
    y: 0,
    x: 0,
    endpoint: ENDPOINTS.OVERVIEW,
    title: TITLES.OVERVIEW,
    displayType: 'summary',
  },
  {
    cols: 1,
    rows: 1,
    y: 0,
    x: 2,
    title: TITLES.PAGEVIEWS,
    event: 'get_pageviews',
    displayType: 'realtime',
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 0,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.VIEWS_BY_TITLE,
    groupBy: 'title',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 1,
    endpoint: ENDPOINTS.EVENTS_GROUPED,
    title: TITLES.EVENTS_BY_NAME,
    groupBy: 'name',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 2,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_COUNTRY,
    groupBy: 'country',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 2,
    x: 0,
    endpoint: ENDPOINTS.ITEM_SOLD,
    title: TITLES.ITEM_SOLD_BY_NAME,
    groupBy: 'name',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 2,
    x: 1,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.SESSIONS_BY_SOURCE,
    groupBy: 'source',
    displayType: 'table',
  },
];