import { DashboardGridItem } from './dashboard-grid-item.interface';
import { DISPLAY_TYPES, ENDPOINTS, EVENT_TYPES, TITLES } from './constants';

export const overviewDashboard: DashboardGridItem[] = [
  {
    cols: 2,
    rows: 1,
    x: 0,
    y: 0,
    endpoint: ENDPOINTS.OVERVIEW,
    title: TITLES.OVERVIEW,
    displayType: DISPLAY_TYPES.SUMMARY,
  },
  {
    cols: 1,
    rows: 1,
    x: 2,
    y: 0,
    title: TITLES.LIVE_SESSIONS,
    event: EVENT_TYPES.SESSIONS,
    displayType: DISPLAY_TYPES.REALTIME,
  },
  {
    cols: 1,
    rows: 1,
    x: 0,
    y: 1,
    title: TITLES.LIVE_VISITORS,
    event: EVENT_TYPES.VISITORS,
    displayType: DISPLAY_TYPES.REALTIME,
  },
  {
    cols: 1,
    rows: 1,
    x: 1,
    y: 1,
    title: TITLES.LIVE_EVENTS,
    event: EVENT_TYPES.EVENTS,
    displayType: DISPLAY_TYPES.REALTIME,
  },
  {
    cols: 1,
    rows: 1,
    x: 2,
    y: 1,
    title: TITLES.LIVE_PAGEVIEWS,
    event: EVENT_TYPES.PAGEVIEWS,
    displayType: DISPLAY_TYPES.REALTIME,
  },
  {
    cols: 1,
    rows: 1,
    x: 0,
    y: 2,
    endpoint: ENDPOINTS.PAGES_GROUPED,
    title: TITLES.VIEWS_BY_TITLE,
    groupBy: 'title',
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 1,
    y: 2,
    endpoint: ENDPOINTS.EVENTS_GROUPED,
    title: TITLES.EVENTS_BY_NAME,
    groupBy: 'name',
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 2,
    y: 2,
    endpoint: ENDPOINTS.VISITORS_GROUPED,
    title: TITLES.VISITORS_BY_COUNTRY,
    groupBy: 'country',
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 0,
    y: 3,
    endpoint: ENDPOINTS.ITEM_SOLD,
    title: TITLES.ITEM_SOLD_BY_NAME,
    groupBy: 'name',
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 1,
    y: 3,
    endpoint: ENDPOINTS.TRAFFIC_GROUPED,
    title: TITLES.SESSIONS_BY_SOURCE,
    groupBy: 'source',
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 2,
    y: 3,
    endpoint: ENDPOINTS.BOUNCE_RATE,
    title: TITLES.BOUNCE_RATE,
    displayType: DISPLAY_TYPES.SINGLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 0,
    y: 4,
    endpoint: ENDPOINTS.AVG_TIME_ON_PAGE,
    title: TITLES.AVG_TIME_ON_PAGE,
    displayType: DISPLAY_TYPES.SINGLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 1,
    y: 4,
    endpoint: ENDPOINTS.UNIQUE_PAGE_VIEWS,
    title: TITLES.UNIQUE_PAGE_VIEWS,
    displayType: DISPLAY_TYPES.SINGLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 2,
    y: 4,
    endpoint: ENDPOINTS.AVG_PAGEVIEWS_PER_SESSION,
    title: TITLES.AVG_PAGEVIEWS_PER_SESSION,
    displayType: DISPLAY_TYPES.SINGLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 0,
    y: 5,
    endpoint: ENDPOINTS.TOP_LANDING_PAGES,
    title: TITLES.TOP_LANDING_PAGES,
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 2,
    rows: 1,
    x: 1,
    y: 5,
    endpoint: ENDPOINTS.BOUNCE_RATE_BY_TITLE,
    title: TITLES.BOUNCE_RATE_BY_TITLE,
    displayType: DISPLAY_TYPES.TABLE,
  },
  {
    cols: 1,
    rows: 1,
    x: 0,
    y: 6,
    endpoint: ENDPOINTS.TOP_EXIT_PAGES,
    title: TITLES.TOP_EXIT_PAGES,
    displayType: DISPLAY_TYPES.TABLE,
  },
];