import { DashboardGridItem } from '../overview/overview.component';

export const overviewDashboard: DashboardGridItem[] = [
  {
    cols: 2,
    rows: 1,
    y: 0,
    x: 0,
    endpoint: 'summary/by-day',
    title: 'Overview Summary',
    displayType: 'summary',
  },
  {
    cols: 1,
    rows: 1,
    y: 0,
    x: 2,
    endpoint: 'realtime/pageviews',
    title: 'Pageviews',
    event: 'get_pageviews',
    displayType: 'realtime',
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 0,
    endpoint: 'pages/by-title',
    title: 'Views by Title',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 1,
    endpoint: 'events/by-name',
    title: 'Events by Name',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 2,
    endpoint: 'visitors/by-country',
    title: 'Visitors by Country',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 2,
    x: 0,
    endpoint: 'ecommerce/items/by-name',
    title: 'Item Sold by Name',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 2,
    x: 1,
    endpoint: 'traffic/by-source',
    title: 'Sessions by Source',
    displayType: 'table',
  },
];