import { DashboardGridItem } from '../overview/overview.component';

export const overviewDashboard: DashboardGridItem[] = [
  {
    cols: 2,
    rows: 1,
    y: 0,
    x: 0,
    endpoint: 'summary/by-day',
    title: 'Overview Summary',
    displayType: 'summary',
  },
  {
    cols: 1,
    rows: 1,
    y: 0,
    x: 2,
    title: 'Pageviews',
    event: 'get_pageviews',
    displayType: 'realtime',
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 0,
    endpoint: 'pages/grouped',
    title: 'Views by Title',
    groupBy: 'title',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 1,
    endpoint: 'events/grouped',
    title: 'Events by Name',
    groupBy: 'name',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 1,
    x: 2,
    endpoint: 'visitors/grouped',
    title: 'Visitors by Country',
    groupBy: 'country',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 2,
    x: 0,
    endpoint: 'ecommerce/items/grouped',
    title: 'Item Sold by Name',
    groupBy: 'name',
    displayType: 'table',
  },
  {
    cols: 1,
    rows: 1,
    y: 2,
    x: 1,
    endpoint: 'traffic/grouped',
    title: 'Sessions by Source',
    groupBy: 'source',
    displayType: 'table',
  },
];