export const ENDPOINTS = {
  OVERVIEW: 'summary/by-day',
  PAGEVIEWS: 'summary/pageviews',
  PAGES_GROUPED: 'pages/grouped',
  BOUNCE_RATE: 'pages/bounce-rate',
  AVG_TIME_ON_PAGE: 'pages/avg-time-on-page',
  UNIQUE_PAGE_VIEWS: 'pages/unique-page-views',
  AVG_PAGEVIEWS_PER_SESSION: 'pages/avg-page-views-per-session',
  TOP_LANDING_PAGES: 'pages/top-landing-pages',
  TOP_EXIT_PAGES: 'pages/top-exit-pages',
  BOUNCE_RATE_BY_TITLE: 'pages/bounce-rate-by-title',
  EVENTS_GROUPED: 'events/grouped',
  VISITORS_GROUPED: 'visitors/grouped',
  ITEM_SOLD: 'ecommerce/items/grouped',
  ITEMS_GROUPED: 'ecommerce/items/grouped',
  SESSIONS_GROUPED: 'sessions/grouped',
  TRAFFIC_GROUPED: 'traffic/grouped',
  SESSIONS_BY_SOURCE: 'sessions/by-source',
};

export const TITLES = {
  OVERVIEW: 'Overview Summary',
  PAGEVIEWS: 'Pageviews',
  VIEWS_BY_TITLE: 'Views by Title',
  PAGES_BY_TITLE: 'Pages by Title',
  PAGES_BY_URL: 'Pages by URL',
  PAGES_BY_REFERRER: 'Pages by Referrer',
  PAGES_BY_DATE: 'Pages by Date',
  BOUNCE_RATE: 'Bounce Rate',
  AVG_TIME_ON_PAGE: 'Avg Time on Page',
  UNIQUE_PAGE_VIEWS: 'Unique Pageviews',
  AVG_PAGEVIEWS_PER_SESSION: 'Avg Pageviews per Session',
  TOP_LANDING_PAGES: 'Top Landing Pages',
  TOP_EXIT_PAGES: 'Top Exit Pages',
  BOUNCE_RATE_BY_TITLE: 'Bounce Rate by Title',
  EVENTS_BY_NAME: 'Events by Name',
  EVENTS_BY_URL: 'Events by URL',
  EVENTS_BY_DATE: 'Events by Date',
  VISITORS_BY_COUNTRY: 'Visitors by Country',
  VISITORS_BY_CITY: 'Visitors by City',
  VISITORS_BY_DEVICE: 'Visitors by Device',
  VISITORS_BY_OS: 'Visitors by OS',
  VISITORS_BY_BROWSER: 'Visitors by Browser',
  ITEM_SOLD_BY_NAME: 'Item Sold by Name',
  ITEMS_BY_ID: 'Items by ID',
  ITEMS_BY_NAME: 'Items by Name',
  ITEMS_BY_CATEGORY: 'Items by Category',
  ITEMS_BY_DATE: 'Items by Date',
  SESSIONS_BY_SOURCE: 'Sessions by Source',
  SESSIONS_BY_COUNTRY: 'Sessions by Country',
  SESSIONS_BY_CITY: 'Sessions by City',
  SESSIONS_BY_DEVICE: 'Sessions by Device',
  SESSIONS_BY_OS: 'Sessions by OS',
  SESSIONS_BY_BROWSER: 'Sessions by Browser',
  SESSIONS_BY_DATE: 'Sessions by Date',
  TRAFFIC_BY_SOURCE: 'Traffic by Source',
  TRAFFIC_BY_MEDIUM: 'Traffic by Medium',
  TRAFFIC_BY_CAMPAIGN: 'Traffic by Campaign',
  TRAFFIC_BY_DATE: 'Traffic by Date',
  LIVE_SESSIONS: 'Live Sessions',
  LIVE_PAGEVIEWS: 'Live Pageviews',
  LIVE_EVENTS: 'Live Events',
  LIVE_VISITORS: 'Live Visitors',
};

// Event Types
export const EVENT_TYPES = {
  SESSIONS: 'live_sessions',
  PAGEVIEWS: 'live_pageviews',
  VISITORS: 'live_visitors',
  EVENTS: 'live_events',
};

export const DISPLAY_TYPES = {
  SUMMARY: 'summary',
  REALTIME: 'realtime',
  TABLE: 'table',
  SINGLE: 'single',
};